#!/bin/bash

warning=10
critical=20

packages=$(
    apt-get --ignore-hold --allow-unauthenticated --dry-run dist-upgrade |
    grep ^Inst |
    cut --delimiter ' ' --fields 2 |
    sort |
    wc --lines
)

if [[ "$packages" -gt "$warning" ]]
then
    echo "$packages packages need upgrading!"
    [[ "$packages" -gt "$critical" ]] && exit 2
    exit 1
else
    echo "$packages packages need upgrading."
fi
