name             'gitlab'
maintainer       'Cogini'
maintainer_email 'nhan@cogini.com'
license          'All rights reserved'
description      'Installs/Configures gitlab'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'build-essential'
depends          'postfix'
depends          'git'
depends          'nginx'
depends          'postgresql'
depends          'python'
