default[:moodle][:site_dir] = '/var/www/moodle'
default[:moodle][:data_dir] = '/var/moodledata'
default[:moodle][:user] = 'nobody'
default[:moodle][:group] = 'nobody'
default[:moodle][:branch] = 'MOODLE_23_STABLE'
